//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMvcDatabaseFirstApproach.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.UsptoClientDatas = new HashSet<UsptoClientData>();
        }
    
        public int PersonId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual ICollection<UsptoClientData> UsptoClientDatas { get; set; }
    }
}
