//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMvcDatabaseFirstApproach.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsptoClientData
    {
        public int UsptoClientDataId { get; set; }
        public int PersonId { get; set; }
        public string UsptoUsername { get; set; }
        public string UsptoPassword { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
